name: safe_route
description: A type-safe Flutter navigation package that adds compile-time checks for route arguments and results.
version: 0.0.2

homepage: https://pub.dev/packages/safe_route
repository: https://github.com/AlexHCJP/safe_route
issue_tracker: https://github.com/AlexHCJP/safe_route/issues

topics:
  - navigation
  - routing
  - typesafety
  - flutter

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0